const Routes = require("express").Router();
const WSSMSSenderRouter = require("./WSSMSSender.routes");
const driversRouter = require("./Drivers.routes");
const PassangerRouter = require("./Passanger.routes");
const VechleRouter = require("./Vechle.routes");
const CancilationRouter = require("./Cancilation.routes");
Routes.use(CancilationRouter);
Routes.use(VechleRouter);
Routes.use(PassangerRouter);
Routes.use(driversRouter);
Routes.use(WSSMSSenderRouter);
module.exports = Routes;
