const Routes = require("express").Router();
const WSSMSSenderRouter = require("./SMSSender.routes");
const VechleRouter = require("./VehicleType.routes");
const CancilationRouter = require("./CancilationReasonsType.routes");
const AdminRouter = require("./Admin.routes");
const userRoutes = require("./User.routes");
const roles = require("./Role.routes");
const Status = require("./Status.routes");
const Vehicles = require("./Vehicle.routes");
const vehicleOwnership = require("./VehicleOwnership.routes");
const Passenger = require("./PassengerRequest.routes");
const Driver = require("./DriverRequest.routes");
const vehicleStatusType = require("./VehicleStatusType.routes");
const userRole = require("./UserRole.routes");
const UserStatuses = require("./UserStatuse.routes");
const UserRoleStatus = require("./UserRoleStatus.routes");
const documentTypes = require("./DocumentTypes.routes");
const attachedDocuments = require("./AttachedDocuments.routes");
const RoleDocumentRequirements = require("./RoleDocumentRequirements.routes");
const database = require("./Database.routes");
const journeyStatus = require("./JourneyStatus.routes");
const canceledJourney = require("./CanceledJourneys.routes");
const JourneyRoutePoints = require("./JourneyRoutePoints.routes");
const paymentMethod = require("./paymentMethod.routes");
const Journey = require("./Journey.routes");
const JourneyDecision = require("./JourneyDecisions.routes");
const Rating = require("./Ratings.routes");
const payments = require("./Payments.routes");
const TarrifRate = require("./TarrifRate.routes");
const driverBalance = require("./DriverBalance.routes");

const TarrifRateForVehcleTypes = require("./TarrifRateForVehcleTypes.routes");
const CommissionRates = require("./CommissionRates.routes");
const Commission = require("./Commission.routes");
const paymentStatus = require("./PaymentStatus.routes");

const DriverDeposit = require("./DriverDeposit.routes");

Routes.use(driverBalance);
Routes.use(paymentStatus);
Routes.use(DriverDeposit);
Routes.use(Commission);
Routes.use(CommissionRates);
Routes.use(TarrifRateForVehcleTypes);
Routes.use(TarrifRate);
Routes.use(payments);
Routes.use(Rating);
Routes.use(JourneyDecision);
Routes.use(Journey);
Routes.use(paymentMethod);
Routes.use(JourneyRoutePoints);
Routes.use(canceledJourney);
Routes.use(journeyStatus);
Routes.use(database);
Routes.use(RoleDocumentRequirements);
Routes.use(attachedDocuments);
Routes.use(documentTypes);
Routes.use(UserRoleStatus);
Routes.use(userRole);
Routes.use(UserStatuses);
Routes.use(vehicleStatusType);
Routes.use(Driver);
Routes.use(Passenger);

Routes.use(vehicleOwnership);

Routes.use(Vehicles);
Routes.use(Status);
Routes.use(roles);
Routes.use(userRoutes);
Routes.use(AdminRouter);
Routes.use(CancilationRouter);
Routes.use(VechleRouter);
Routes.use(WSSMSSenderRouter);
module.exports = Routes;
