const Routes = require("express").Router();
const WSSMSSenderRouter = require("./SMSSender.routes");
const VechleRouter = require("./VechleType.routes");
const CancilationRouter = require("./CancilationReasonsType.routes");
const AdminRouter = require("./Admin.routes");
const userRoutes = require("./User.routes");
const roles = require("./Role.routes");
const Status = require("./Status.routes");
const Vehicles = require("./vehicle.routes");
const vehicleOwnership = require("./vehicleOwnership.routes");
const Passenger = require("./PassengerRequest.routes");
const Driver = require("./DriverRequest.routes");
const vehicleStatusType = require("./vehicleStatusType.routes");
const userRole = require("./userRole.routes");
const UserStatuses = require("./userStatuse.routes");
const UserRoleStatus = require("./UserRoleStatus.routes");
const documentTypes = require("./documentTypes.routes");
const attachedDocuments = require("./attachedDocuments.routes");
const RoleDocumentRequirements = require("./RoleDocumentRequirements.routes");
const database = require("./Database.routes");
const journeyStatus = require("./JourneyStatus.routes");
const canceledJourney = require("./CanceledJourneys.routes");
const JourneyRoutePoints = require("./JourneyRoutePoints.routes");
const paymentMethod = require("./paymentMethod.routes");
const Journey = require("./Journey.routes");
const JourneyDecision = require("./JourneyDecisions.routes");
const Rating = require("./Ratings.routes");

Routes.use(Rating);
Routes.use(JourneyDecision);
Routes.use(Journey);
Routes.use(paymentMethod);
Routes.use(JourneyRoutePoints);
Routes.use(canceledJourney);
Routes.use(journeyStatus);
Routes.use(database);
Routes.use(RoleDocumentRequirements);
Routes.use(attachedDocuments);
Routes.use(documentTypes);
Routes.use(UserRoleStatus);
Routes.use(userRole);
Routes.use(UserStatuses);
Routes.use(vehicleStatusType);
Routes.use(Driver);
Routes.use(Passenger);

Routes.use(vehicleOwnership);

Routes.use(Vehicles);
Routes.use(Status);
Routes.use(roles);
Routes.use(userRoutes);
Routes.use(AdminRouter);
Routes.use(CancilationRouter);
Routes.use(VechleRouter);
Routes.use(WSSMSSenderRouter);
module.exports = Routes;
