const Config = require("./Config");
//constants;

const REDIS_SOCKET_PATH = process.env.REDIS_SOCKET_PATH || "";
const UPSTASH_REDIS_URL = Config.REDIS.URL;

// HTTP Status Codes
// Single source of truth — Utils/AppError re-exports these as AppError.OK,
// AppError.BAD_REQUEST, ... so existing AppError throws can reference them
// without an extra import.
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  GONE: 410,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
};

// Domain rules
const DOMAIN = {
  OTP_LENGTH: 6,
  MAX_RATING: 5,
  MAX_INDIVIDUAL_TARGET_VEHICLES: 9,
  USER_SEARCH_FIELD_COUNT: 9,
  PHONE_NUMBER_LENGTH: 9,
  EMAIL_VERIFICATION_EXPIRY_HOURS: 2,
  DEFAULT_QUEUE_REFUSAL_LIMIT: 3,
  RESPONSE_DEADLINE_DEFAULT_DAYS: 5,
  PHONE_MASK_KEEP_FIRST: 3,
  PHONE_MASK_KEEP_LAST: 2,
  PHONE_COUNTRY_CODE_LENGTH: 3,
  DECIMAL_PLACES: 2,
  MAX_VARCHAR_LENGTH: 255,
  LATITUDE_MIN: -90,
  LATITUDE_MAX: 90,
  LONGITUDE_MIN: -180,
  LONGITUDE_MAX: 180,
  MAX_COMMENT_LENGTH: 500,
  MAX_SHORT_TEXT_LENGTH: 50,
  MAX_PHONE_LENGTH: 20,
  MAX_LONG_TEXT_LENGTH: 2000,
  MAX_NAME_LENGTH: 100,
  MAX_REQUEST_VEHICLES: 100,
  MAX_PERCENTAGE: 100,
  MAX_MONEY_AMOUNT: 999999.99,
  MIN_RESPONSE_LENGTH: 10,
  BCRYPT_SALT_ROUNDS: 10,
};

// Pagination
const PAGINATION = {
  DEFAULT_PAGE_SIZE: 10,
  BATCH_DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  ABSOLUTE_MAX_LIMIT: 1000,
};

// MongoDB driver error codes
const MONGO_ERROR = {
  DUPLICATE_KEY: 11000,
};

// Time durations in milliseconds
const TIME = {
  MINUTE_MS: 60000, // 60 * 1000
  HOUR_MS: 3600000, // 60 * 60 * 1000
  DAY_MS: 86400000, // 24 * 60 * 60 * 1000
  FIVE_MINUTES_MS: 300000, // 5 * 60 * 1000
  FIFTEEN_MINUTES_MS: 900000, // 15 * 60 * 1000
  MILLISECONDS_PER_SECOND: 1000,
};

module.exports = {
  REDIS_SOCKET_PATH,
  UPSTASH_REDIS_URL,
  HTTP_STATUS,
  DOMAIN,
  PAGINATION,
  TIME,
  MONGO_ERROR,
};
