// Utils/SocketUserTypes.js
//
// Single source of truth for the socket user types accepted/generated by the
// WebSocket layer. `WSPusher` validates clients against these exact strings,
// socket registrations are keyed `${userType}:${phone}`, and every notification
// helper looks a socket up by the same key — never duplicate a literal.

const SocketUserTypes = {
  DRIVER: "driver",
  SHIPPER: "shipper",
  SMSSENDER: "SMSSender",
  ADMIN: "admin",
  COMPANY: "company",
  QUEUE_ORG_ADMIN: "queueOrgAdmin",
};

// The exhaustive list of types a client may present while connecting.
const VALID_USER_TYPES = Object.values(SocketUserTypes);

module.exports = { SocketUserTypes, VALID_USER_TYPES };